---
- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Initialize the cluster using kubeadm
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu

    - name: Fetch admin.conf to local
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./admin.conf
        flat: yes

    - name: Update Master IP and security in local admin.conf
      delegate_to: localhost
      become: false
      shell: |
        if grep -q "https://{{ ansible_host }}:6443" ./admin.conf && grep -q "insecure-skip-tls-verify: true" ./admin.conf; then
          echo "admin.conf already updated"
          exit 0
        fi
        sed -i '' 's|https://.*:6443|https://{{ ansible_host }}:6443|g' ./admin.conf
        sed -i '' 's|certificate-authority-data:.*|insecure-skip-tls-verify: true|g' ./admin.conf
      args:
        executable: /bin/bash
      register: sed_output
      changed_when: "'already updated' not in sed_output.stdout"

    - name: Install Pod Network (Flannel)
      become: false
      command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      register: flannel_apply
      changed_when: "'created' in flannel_apply.stdout or 'configured' in flannel_apply.stdout"

    - name: Get join command from master
      command: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: false

    - name: Set join command as a fact
      set_fact:
        join_command: "{{ join_command_raw.stdout }}"

    - name: Create S3 Secret in Kubernetes
      become: false
      shell: |
        kubectl create secret generic s3-credentials \
        --from-literal=S3_BUCKET_NAME={{ s3_bucket_name }} \
        --from-literal=AWS_REGION={{ aws_region }} \
        --save-config --dry-run=client -o yaml | kubectl apply -f -
      register: secret_apply
      changed_when: "'created' in secret_apply.stdout or 'configured' in secret_apply.stdout"

- name: Join Workers to Cluster
  hosts: workers
  become: yes
  tasks:
    - name: Join worker nodes to the cluster
      command: "{{ hostvars['master-node'].join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf